### ISSUE TITLE
javax.mail.Provider: Provider com.sun.mail.imap.IMAPProvider not found

### ISSUE THREAD

**Issue by Inno-DAC** [baloise/digital-signature#44]
[error.zip](https://github.com/baloise/digital-signature/files/3972410/error.zip)

Digital-signature fails to send notification email upon signature : it lacks the javax.mail dependency.
Confluence notification emails are working fine though.

Environnement :
- Confluence 7.1 server
- digital-signature 0.10.3

Environnement Java Runtime
Linux 4.15.0-72-generic
amd64
Apache Tomcat/9.0.27
4.0
Java 1.8.0_202
AdoptOpenJdk
JVM1.8
JVMOracle Corporation
JVM25.202-b08
Runtime JavaOpenJDK Runtime Environment
VM JavaOpenJDK 64-Bit Server VM
Arguments Java Runtime 
-Djava.util.logging.config.file=/opt/atlassian/confluence/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -XX:ReservedCodeCacheSize=256m -XX:+UseCodeCacheFlushing -Djdk.tls.server.protocols=TLSv1.1,TLSv1.2 -Djdk.tls.client.protocols=TLSv1.1,TLSv1.2 -Dconfluence.context.path= -Datlassian.plugins.startup.options= -Djava.locale.providers=JRE,SPI,CLDR -Dorg.apache.tomcat.websocket.DEFAULT_BUFFER_SIZE=32768 -Dsynchrony.enable.xhr.fallback=true -Xms1024m -Xmx1024m -XX:+UseG1GC -Datlassian.plugins.enable.wait=300 -Djava.awt.headless=true -XX:G1ReservePercent=20 -Xloggc:/opt/atlassian/confluence/logs/gc-2019-12-16_10-37-13.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=2M -Xlog:gc+age=debug:file=/opt/atlassian/confluence/logs/gc-2019-12-16_10-37-13.log::filecount=5,filesize=2M -XX:-PrintGCDetails -XX:+PrintGCDateStamps -XX:-PrintTenuringDistribution -XX:+IgnoreUnrecognizedVMOptions -Dignore.endorsed.dirs= -Dcatalina.base=/opt/atlassian/confluence -Dcatalina.home=/opt/atlassian/confluence -Djava.io.tmpdir=/opt/atlassian/confluence/temp

**Comment by krispn24** [comment]
We're getting the same error. Any suggested fixes, thus far?

**Comment by MarkusTiede** [comment]
No not yet.

Thanks for noticing and sorry for the delay - @Tiliavir: Would you mind having a look into this next thursday (aka. our [open-source thursday](https://opensourcefriday.com/)?

**Comment by Tiliavir** [comment]
Most probably a version issue (digital-signature was built against 6.x).
Will try to upgrade the solution as soon as possible.

Easiest approach seems to be to use the Atlassian SDK to create a "new" confluence plugin and move our code afterwards:

`.\atlas-create-confluence-plugin.bat -a digital-signature -g com.baloise.confluence -v 7.0.0`

**Comment by culmat** [comment]
Hello InnoDac,

thanks again for reporting this issue. We released the fix [as V7.0.0 on the marketplace](https://marketplace.atlassian.com/apps/1217404/digital-signature/version-history).

Enjoy.
Markus & Matthias

**Comment by MarkusTiede** [comment]
Hey @Inno-DAC & @krispn24 - do you have any updates whether it's working now? Thanks for a quick feedback!

**Comment by Inno-DAC** [comment]
Still not working, same Error.
Tested using Confluence 7.2.0, Digital-Signature 7.0.0
![Annotation 2020-05-07 135614](https://user-images.githubusercontent.com/58973199/81292359-c210c200-906b-11ea-825e-24cd9db87c74.jpg)

**Comment by MarkusTiede** [comment]
Thanks for the quick update - @Tiliavir : would you mind having a look again / asking e.g. for more details / logs to trace this issue down?

**Comment by culmat** [comment]
Hello @Inno-DAC & @krispn24 
I have been able to reproduce and fix this. Please update to https://marketplace.atlassian.com/apps/1217404/digital-signature/version-history
Best regards.
Matthias

**Comment by Inno-DAC** [comment]
working like a charm ! Thank you for your great job

**Comment by MarkusTiede** [comment]
Thanks for fixing @culmat and for confirmation that it works @Inno-DAC : would you be interested giving us / the plugin a review in the [Atlassen marketplace](https://marketplace.atlassian.com/apps/1217404/digital-signature?hosting=server&tab=reviews)?
